[package]
name = "txb2json"
description = "TXB to JSON converter (and back)"
version = "0.9.0"
edition = "2024"
authors = ["Oleg \"OSA413\" Sokolov"]
repository = "https://github.com/OSA413/Sonic4_Tools"
homepage = "https://github.com/OSA413/Sonic4_Tools"
license = "MIT"

[dependencies]
txb-rs-lib = { path = "../txb-rs-lib" }
common_binary = { path = "../common_binary" }
