[workspace]
members = [
    "src/common/utils",
    "src/common/binary",

    "src/amb/amb-rs",
    "src/amb/amb-rs-lib",
    "src/amb/amb-rs-tests",

    "src/txb/txb-rs-lib",
    "src/level_layout_tools/dc/dc-rs-lib",
    "src/level_layout_tools/ev/ev-rs-lib",
    "src/level_layout_tools/md/md-rs-lib",
    "src/level_layout_tools/mp/mp-rs-lib",
    "src/level_layout_tools/rg/rg-rs-lib",
    
    "src/txb/txb2json",
    "src/level_layout_tools/dc/dc2json",
    "src/level_layout_tools/ev/ev2json",
    "src/level_layout_tools/md/md2json",
    "src/level_layout_tools/mp/mp2json",
    "src/level_layout_tools/rg/rg2json",
]
resolver = "3"