[package]
name = "txb-rs-lib"
description = "TeXture Bank library"
edition = "2024"
version = "0.1.0"
authors = ["Oleg \"OSA413\" Sokolov"]
repository = "https://github.com/OSA413/Sonic4_Tools"
homepage = "https://github.com/OSA413/Sonic4_Tools"
license = "MIT"

[dependencies]
common_binary = { path = "../../common/binary" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"