name: Midday build (Windows)

on:
  push:
    branches:
     - "**"
  pull_request:
    branches:
     - "**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Update dependencies
        run: bash update_dependencies.sh

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - run: msbuild ./Sonic4_Tools/Sonic4_Tools.sln /p:Configuration=Release -m

      - name: Build
        run: bash build_pack.sh
        
      - uses: actions/upload-artifact@v7
        with:
          name: Tools
          path: dist/*.7z

      - uses: actions/upload-artifact@v7
        with:
          name: SHA256 sums
          path: dist/SHA256SUMS
