name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        python3 fix_sh_newline.py
        bash update_dependencies.sh
        bash build_pack.sh
    
    - name: Upload artifact (Main)
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Sonic4_Tools.7z
        path: dist/Sonic4_Tools.7z

    - name: Upload artifact (SHA256 sums)
      uses: actions/upload-artifact@v1.0.0
      with:
        name: SHA256SUMS
        path: dist/SHA256SUMS
